[build-system]
requires = ["uv_build>=0.12.16,<0.13"]
build-backend = "uv_build"

[project]
name = "starter-code-openzh-generator"
version = "0.1.0"
description = "Automatically generate Python and R starter code for Open Government Data Shops"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=3.0.0",
    "pyyaml>=6.0.3",
    "requests>=2.32.5",
    "typer>=0.21.1",
]

[tool.uv]
exclude-newer = "7 days"

[tool.uv.build-backend]
source-include = ["config.yaml", "_templates/**", "tests/**"]

[project.scripts]
updater = "starter_code_openzh_generator.updater:app"

[tool.ruff]
line-length = 100
target-version = "py313"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff.lint]
select = ["E", "F", "I", "N", "W", "UP"]

[dependency-groups]
dev = [
    "matplotlib>=3.11.2",
    "pytest>=9.1.1",
    "ruff>=0.14.14",
    "seaborn>=0.13.2",
]
